### ISSUE TITLE
Add regex filtering

### ISSUE THREAD

**Issue by Ben-Lichtman** [entropic-security/xgadget#1]
Instead of matching on a fixed string we should be able to match on a regex

**Comment by tnballo** [comment]
Agreed! Had considered using t[he `regex` crate](https://crates.io/crates/regex) for this but haven't gotten around to it yet. Will do, this weekend at the earliest. 

Thanks!

**Comment by tnballo** [comment]
Added in 3d9427b. Tested using a "pop pop ret" regex: `^(?:pop)(?:.*(?:pop))*.*ret`.
